name: mock_vehicle_server
description: "Standalone mock MAVLink vehicle + Silvus radio servers for GCS testing"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

executables:
  mock_vehicle_server: mock_vehicle_server
  mock_radio_server: mock_radio_server

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  scout_mavlink_dart:
    path: ../scout-td0-mavlink-data-model-generator/packages/scout_mavlink_dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
