name: mock_vehicle_server
description: "Standalone mock MAVLink vehicle UDP server for GCS testing"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mavlink_dart:
    git:
      url: https://github.com/satheesh-kumar-p/mavlink_dart
      ref: v0.0.5-alpha.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
